"""empty message

Revision ID: e14bc4533272
Revises: 9878e27a26de
Create Date: 2017-10-15 19:07:10.533220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e14bc4533272'
down_revision = '9878e27a26de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('is_standlone', sa.Boolean(), nullable=True))
    op.drop_column('types', 'standlone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('standlone', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('types', 'is_standlone')
    # ### end Alembic commands ###
